### PR TITLE
PR for #1: Revise histogram to display proportions instead of counts (#2)

### LINKED ISSUE #1: Revise histogram of chips sold to show proportions
See task description [here](https://github.com/gslab-econ/ra-manual/wiki/Practice-Task). The goal is to revise the histogram in [`/data/output/chips_sold.pdf`](https://github.com/snairdesai/sameer_template/blob/main/data/output/chips_sold.pdf) to display percentage values on the y-axis, rather than counts. The relevant code to check here is in [`/data/code/clean_data.py`](https://github.com/snairdesai/sameer_template/blob/issue1_prop_hist/data/code/clean_data.py).

### PR DESCRIPTION
**Pull request by snairdesai**
**Closes #1**

--------------------------------------------------------------------------------------------------

@jc-cisneros @anacarolinapq Issuing a pull request here to resolve Issue #1. All relevant changes have been made in [`issue1_prop_hist`](https://github.com/snairdesai/sameer_template/tree/issue1_prop_hist), within the file `/data/code/clean_data.py`, in commit [`47bc5ac`](https://github.com/snairdesai/sameer_template/commit/47bc5acce03ae00fad4457e9d01f3217e124d3db).

### CODE REVIEW

**Comment by snairdesai** [comment]
Also noting @anacarolinapq I issued the commits during practice (so before realizing we were meant to assign you). I understand these naming formats should follow the guidance in [`gslab_ra-manual`](https://github.com/gslab-econ/ra-manual/wiki/Workflow).

**Comment by anacarolinapq** [comment]
@snairdesai says:

> Also noting @anacarolinapq I issued the commits during practice (so before realizing we were meant to assign you). I attempted to change commit titles after the fact, but [GitHub highly discourages this](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message). I understand these naming formats should follow the guidance in [gslab-econ/ra-manual](https://github.com/gslab-econ/ra-manual/wiki/Workflow).

Okay, thank you for letting me know! What I usually do when I forget to add the `#commit-number` is just make a comment on the commit itself tagging the issue (this way, it still appears on the issue thread!)

**Comment by anacarolinapq** [comment]
@snairdesai two other notes: 

1. To assign a peer reviewer, you should assign them on the `Reviewer` tab, not the `Assignee` tab. Per [the RA manual](https://github.com/gslab-econ/lab-manual/wiki/Workflow#pull-request), the assignee should be the person originally assigned to the issue. I will make these changes here, and it would be great if you could keep these in mind for future PRs. Thanks! 
2. On the initial PR comment, it is good practice to also let the reviewer know if there are any particular aspects of the code that you would like to have reviewed + what the ideal result of the review should be, or if the basic peer review would suffice. The same holds if there are a lot of changes to the repo. Per [here](https://github.com/gslab-econ/lab-manual/wiki/Workflow#peer-review), the reviewer should not go over every line of code unless explicitly asked, so if you would like more in-depth review, for example to a new function, you should let the reviewer know and also give guidance on what the correct behavior of the function should be, so the reviewer can check it.

Thanks!

**Review by anacarolinapq — APPROVED** [review]
All changes look good, thanks!

**Pull request merged**
